data_ingestion:
  kaggle_dataset_url: 'https://www.kaggle.com/datasets/briscdataset/brisc2025'
  raw_data_manifest: 'artifacts/manifests'

classification:
  image_size: 224
  batch_size: 64
  num_workers: 0

segmentation:
  image_size: 512
  batch_size: 8
  num_workers: 0

model_trainer:
  num_classes: 4
  epoch: 30
  learning_rate: 0.001
  checkpoint_dir: 'artifacts/objects'

model_evaluation:
  checkpoint_dir: 'artifacts/objects/classification.pth'
  num_classes: 4